version: "3.3"

services:
  wireguard:
    image: "embarkstudios/wireguard-ui"
    container_name: "wireguard"
    restart: unless-stopped
    privileged: true
    volumes:
      - "./data/wg:/var/lib/wireguard-ui"
    environment:
      # заменить domain.com на свой
      WIREGUARD_UI_WG_ENDPOINT: dvkotin.com:443
      WIREGUARD_UI_LOG_LEVEL: debug
      WIREGUARD_UI_NAT_DEVICE: eth0
      WIREGUARD_UI_WG_LISTEN_PORT: 443
      WIREGUARD_UI_WG_DNS: 8.8.8.8
    ports:
      - "443:443/udp"
    labels:
      - "traefik.enable=true"
      # заменить domain.com на свой
      - "traefik.http.routers.wireguard.rule=Host(`dvkotin.com`)"
      - "traefik.http.routers.wireguard.entrypoints=websecure"
      - "traefik.http.routers.wireguard.tls.certresolver=le"
      - "traefik.http.services.wireguard.loadbalancer.server.port=8080"
      - "traefik.http.routers.wireguard.middlewares=ipwhitelist,basicauth"

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: unless-stopped
    command:
          - "--api.insecure=false"
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--providers.docker.network=traefik-hub"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
          - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
          - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
            # Sertificates
            # - "--entrypoints.https.http.tls.certResolver=le"
          - "--certificatesresolvers.le.acme.tlschallenge=true"
          # заменить email на свой
          - "--certificatesresolvers.le.acme.email=dvkotin@gmail.com"
          - "--certificatesresolvers.le.acme.storage=/data/acme.json"
          - "--log.level=DEBUG"
    ports:
          - "80:80"
          - "443:443"
    volumes:
          - "./data/traefik:/data"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
    extra_hosts:
          - host.docker.internal:host-gateway
    labels:
          - "traefik.enable=true"
          # вайтлист ip для админки
          - "traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange=0.0.0.0/0"
          # сгенерить basicauth командой:
          # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
          # ВАЖНО СЛОЖНЫЙ ПАРОЛЬ
          - "traefik.http.middlewares.basicauth.basicauth.users=user:pass"
          - "traefik.http.middlewares.basicauth.basicauth.headerField=X-Forwarded-User"
          # NEW
          - "traefik.http.routers.traefik.entrypoints=websecure"
          - "traefik.http.routers.traefik.rule=Host(`tr.dvkotin.com`)"
          - "traefik.http.routers.traefik.tls=true"
          - "traefik.http.routers.traefik.tls.certresolver=le"
          - "traefik.http.routers.traefik.service=api@internal"
          - "traefik.http.services.traefik-traefik.loadbalancer.server.port=888"
          - "traefik.http.middlewares.traefik-auth.basicauth.users=user:pass"
          - "traefik.http.routers.traefik.middlewares=traefik-auth"

networks:
  default:
    name: traefik-hub
    external: true
