version: "3"

services:
  wireguard:
    image: "embarkstudios/wireguard-ui"
    container_name: "wireguard"
    restart: unless-stopped
    privileged: true
    volumes:
      - "./data/wg:/var/lib/wireguard-ui"
    environment:
      # заменить domain.com на свой
      WIREGUARD_UI_WG_ENDPOINT: dvkotin.com:443
      WIREGUARD_UI_LOG_LEVEL: debug
      WIREGUARD_UI_NAT_DEVICE: eth0
      WIREGUARD_UI_WG_LISTEN_PORT: 443
      WIREGUARD_UI_WG_DNS: 8.8.8.8
    ports:
      - "443:443/udp"
    labels:
      - "traefik.enable=true"
      # заменить domain.com на свой
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.wireguard.rule=Host(`dvkotin.com`)"
      - "traefik.http.routers.wireguard.entrypoints=https"
      - "traefik.http.routers.wireguard.tls.certresolver=letsEncrypt"
      - "traefik.http.services.wireguard.loadbalancer.server.port=8080"
      - "traefik.http.routers.wireguard.middlewares=ipwhitelist,basicauth"
    networks:
      - traefik-hub
    depends_on:
      - traefik

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
          - "./data/traefik:/data"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "./data/traefik.yml:/traefik.yml:ro"
          - "./ssl:/ssl"
    extra_hosts:
          - host.docker.internal:host-gateway
    ports:
      - 80:80
      - 443:443
    labels:
          - "traefik.enable=true"
          # вайтлист ip для админки
          - "traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange=0.0.0.0/0"
          # сгенерить basicauth командой:
          # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
          # ВАЖНО СЛОЖНЫЙ ПАРОЛЬ
          - "traefik.http.middlewares.basicauth.basicauth.users=username:pass"
          - "traefik.http.middlewares.basicauth.basicauth.headerField=X-Forwarded-User"
          # New:
          - "traefik.http.routers.traefik.entrypoints=https"
          - "traefik.http.routers.traefik.rule=Host(`tr.dvkotin.com`)"
          - "traefik.http.routers.traefik.tls=true"
          - "traefik.http.routers.traefik.tls.certresolver=letsEncrypt"
          - "traefik.http.routers.traefik.service=api@internal"
          - "traefik.http.services.traefik-traefik.loadbalancer.server.port=888"
          - "traefik.http.middlewares.traefik-auth.basicauth.users=username:pass"
          - "traefik.http.routers.traefik.middlewares=traefik-auth"
    networks:
      - traefik-hub

networks:
  traefik-hub: {}
  traefik-networks:
    external: true
